# Generated by Django 4.2.14 on 2024-11-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_article_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipaddress',
            options={'verbose_name': 'آی پی آدرس', 'verbose_name_plural': 'آی پی آدرس ها'},
        ),
    ]
