# Generated by Django 4.2.14 on 2024-11-28 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0013_alter_blockeduser_id_alter_blockeduserhistory_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockeduser',
            options={'verbose_name': 'کاربر مسدود ', 'verbose_name_plural': 'کاربران مسدود'},
        ),
        migrations.AlterModelOptions(
            name='blockeduserhistory',
            options={'verbose_name': 'تاریخچه کاربر مسدود', 'verbose_name_plural': 'تاریخچه کاربران مسدود'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted'], 'verbose_name': 'دیدگاه', 'verbose_name_plural': 'دیدگاه ها'},
        ),
        migrations.AlterModelOptions(
            name='flag',
            options={'verbose_name': 'پرچم', 'verbose_name_plural': 'پرچم ها'},
        ),
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name': 'دنبال کننده', 'verbose_name_plural': 'دنبال کنندگان ها'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': 'واکنش', 'verbose_name_plural': 'واکنش ها'},
        ),
    ]
